---
- name: install maven
  become: yes
  apt:
    name: maven
    state: present

- name: Download google chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb

- name: Install google chrome
  become: yes
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
