- hosts: checkbox
  gather_facts: yes
  become: yes
  vars:
    ansible_python_interpreter: python3
  vars_files:
    - /bakerx/cm/vars/vars.yml

  roles:
    - ping   
    - checkbox.io
    - pm2_setup    
    - checkbox_deploy
   