---
- hosts: localhost
  roles:
    - iTrust_build

- hosts: itrust
  become: yes
  
  vars_files:
    - /bakerx/cm/vars/vars.yml

  roles:
    - ping
    - java    
    - mysql
    - setup_itrust
    - tomcat