---
- name: Specify MySQL root password before installing MySQL
  become: yes
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: '{{ mysql_pwd }}'
    vtype: password

- name: MySQL root password confirmation
  become: yes
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: '{{ mysql_pwd }}'
    vtype: password

- name: Install MySQL server
  become: yes
  apt:
    name: mysql-server
    state: present

- name: Install MySQL client
  become: yes
  apt:
    name: mysql-client
    state: present

- name: Restart the MySQL service
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: true