---

- name: stat for /opt/tomcat9
  stat:
    path: /opt/tomcat9
  register: tomcatPath

- name: Get tomcat installation tar
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M27/bin/apache-tomcat-9.0.0.M27.tar.gz
    dest: /opt
  when: tomcatPath.stat.exists == False

- name: Unzip the tar
  unarchive:
    remote_src: yes
    src: /opt/apache-tomcat-9.0.0.M27.tar.gz
    dest: /opt
  when: tomcatPath.stat.exists == False

- name: Rename the extracted tar
  command: mv apache-tomcat-9.0.0.M27 tomcat9
  args:
    chdir: /opt
  when: tomcatPath.stat.exists == False

- name: Configure tomcat users
  copy:
    src: /bakerx/cm/roles/tomcat/templates/tomcat-users.xml
    dest: /opt/tomcat9/conf/tomcat-users.xml
    mode: 0500

- name: Copy iTrust war file to Tomcat webapps folder
  copy:
    src: "/bakerx/cm/roles/create_jobs/templates/iTrust2.war"
    dest: /opt/tomcat9/webapps/
    force: yes

- name: Start Tomcat service
  shell: nohup sh /opt/tomcat9/bin/startup.sh