---

- name: clone checkbox.io repo
  git: 
    repo: 'https://github.com/chrisparnin/checkbox.io.git'
    dest: '/checkbox'
    update: no

- name: Installing express
  become: true
  apt:
    name: ['node-express-generator']
    state: present

- name: Copy nginx configuration file 
  template:  
    src: default.conf.j2
    dest: '/etc/nginx/sites-available/checkbox'
  

- name: remove default site of nginx
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: delete checkbox application if it already exists in nginx
  file:
    path: '/etc/nginx/sites-enabled/checkbox'
    state: absent

- name: Creating simlink
  file:
    src: "/etc/nginx/sites-available/checkbox"
    dest: "/etc/nginx/sites-enabled/checkbox"
    state: link 

- name: Copy html files
  copy: 
    src: "/checkbox/public_html"
    dest: /usr/share/nginx/html
    remote_src: yes
  
- name: Restart NGINX
  service:
    state: restarted
    enabled: true
    name: nginx

- name: install node modules
  npm:
    path: /checkbox
    state: latest

- name: install node modules
  npm:
    path: /checkbox/server-side/site
    state: latest
    
- name: stop checkbox if it is already running
  shell: pm2 kill

- name: start checkbox
  shell: pm2 start server.js
  args:
    chdir: /checkbox/server-side/site
