---

- name: Install aws-cli
  pip:
    name: awscli
    state: present

- name: Install boto3 
  pip:
    name: boto3
    state: present

- name: Make .aws directory
  file:
    path: "/home/vagrant/.aws"
    state: directory
    owner: vagrant
    group: vagrant

- name: Make provision directory
  file:
    path: "/home/vagrant/provision"
    state: directory

- name: Copy aws credentials file
  template:
    src: /bakerx/provision/roles/provision_setup/templates/aws_credentials.j2
    dest: "/home/vagrant/.aws/credentials"

- name: Copy aws configuration files
  template:
    src: /bakerx/provision/roles/provision_setup/templates/aws_config.j2
    dest: "/home/vagrant/.aws/config"

- name: Copy vm creation python program
  copy:
    src: /bakerx/provision/roles/provision_setup/templates/provision_aws_vms.py
    dest: "/home/vagrant/provision"

- name: Set REGION 
  lineinfile:
    dest: /etc/environment
    line: AWS_REGION={{ AWS_REGION }}
    regexp: "^AWS_REGION"
    state: present

- name: Set ACCESS KEY ID 
  lineinfile:
    dest: /etc/environment
    line: AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
    regexp: "^AWS_ACCESS_KEY_ID"
    state: present

- name: Set AWS SECRET ACCESS KEY 
  lineinfile:
    dest: /etc/environment
    line: AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
    regexp: "^AWS_SECRET_ACCESS_KEY"
    state: present

- name: Copy keypair 
  copy:
    src: /bakerx/provision/roles/provision_setup/templates/ec2-keypair.pem
    dest: "/home/vagrant/ec2-keypair.pem"

- name: provision VM(s)
  shell: python3 /home/vagrant/provision/provision_aws_vms.py
  become: true

- name: Wait for the VMs to load
  pause:
    minutes: 1

- name: Get servers json file
  fetch:
    src: "/home/vagrant/servers.json"
    dest: "/bakerx/"
    flat: yes

- name: Copy keypair to .ssh folder of config-srv
  copy:
    src: "/bakerx/provision/roles/provision_setup/templates/ec2-keypair.pem"
    dest: "/home/vagrant/.ssh/ec2-keypair"
    owner: vagrant
    group: vagrant
    mode: u=r--,g=---,o=---

- name: Fetch inventory.ini 
  fetch:
    src: "/home/vagrant/inventory.ini"
    dest: /bakerx/
    flat: yes


