- name: Copy the Fuzzer class file to jenkins-srv
  copy:
    src: /bakerx/cm/fuzzer.js
    dest: /home/vagrant/fuzzer.js

- name: Copy driver js code for test prioritization analysis
  copy:
    src: /bakerx/cm/mutation_driver.js
    dest: /home/vagrant/mutation_driver.js

- name: Setup MySQL Configurations
  copy:
    dest: /home/vagrant/mysql_config.txt
    content: |
      [client]
      user={{ mysql_user }}
      password={{ mysql_pwd }}

- name: Copy package.json 
  copy:
    src: /bakerx/fuzzing/package.json
    dest: package.json

- name: Install required node packages
  shell: npm install
