---
- name: Run whoami
  command: whoami
  changed_when: false
  become: no
  register: whoami

- name: Copy the server file
  copy:
    src: /bakerx/servers.json
    dest:  /home/{{ whoami.stdout}}

- name: Copy nginx configuration file 
  template:  
    src: default.conf.j2
    dest: '/etc/nginx/sites-enabled/'

- name: remove default site of nginx
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: Restart NGINX
  service:
    state: restarted
    enabled: true
    name: nginx

- name: Copy the redis file
  copy:
    src: /bakerx/cm/redis.sh
    dest:  /home/{{ whoami.stdout}}

- name: configure redis
  become: yes
  shell : chmod 700 /home/{{ whoami.stdout}}/redis.sh && /home/{{ whoami.stdout}}/redis.sh

- name: Copy folder
  copy:
    src: /bakerx/provision/roles/monitor_setup/templates/dashboard
    dest: /home/{{ whoami.stdout}}

- name: Install npm packages
  shell: "cd /home/{{ whoami.stdout}}/dashboard && sudo npm install"
  become: yes

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest
  become: yes

- name: Run bin/www forever
  shell: "cd /home/{{ whoami.stdout}}/dashboard && forever stopall && forever start bin/www"