---
- name: Copy Dashboard Code
  copy: 
    src: "/bakerx/Monitoring/dashboard"
    dest: /home/vagrant/   

- name: Do npm install
  npm:
    path: "/home/vagrant/dashboard" 

- name: Copy nginx configuration file 
  template:  
    src: default.conf.j2
    dest: '/etc/nginx/sites-enabled/'

- name: Remove default site of nginx
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: Restart NGINX
  service:
    state: restarted
    enabled: true
    name: nginx
