---
- name: Clone the repository
  git:
    repo: "https://github.com/chrisparnin/checkbox.io-micro-preview.git"
    dest: "/home/vagrant/checkbox"
  become: true

- name: Do npm install /home/vagrant/checkbox
  npm:
    path: "/home/vagrant/checkbox"

- name: Copy Agent
  copy:
    src: /bakerx/Monitoring/agent
    dest: "/home/vagrant"

- name: Do npm install /home/vagrant/agent
  npm:
    path: "/home/vagrant/agent"
