- name : Register file - blue
  local_action:
    module: stat
    path: home/vagrant/blue.json
  register: blue_file
  become: no

- name: fetch blue.json file
  fetch: 
    src: "/home/vagrant/blue.json"
    dest: /bakerx/canary/
    flat: yes  
  when: blue_file.stat.exists == False

- name : Register file - green
  local_action:
    module: stat
    path: home/vagrant/blue.json
  register: green_file
  become: no

- name: fetch green.json file
  fetch: 
    src: "/home/vagrant/green.json"
    dest: /bakerx/canary/
    flat: yes 
    when: green_file.stat.exists == False

- name: Remove blue.json
  file:
    path: /home/vagrant/blue.json
    state: absent

- name: Remove green.json
  file:
    path: /home/vagrant/green.json
    state: absent