---
- name: Adding the java repository
  become: yes
  apt_repository: 
    repo: 'ppa:openjdk-r/ppa'

- name: Run apt update
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: install openjdk
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
